### ISSUE TITLE
Unable to upload images

### ISSUE THREAD

**Issue by malopez00** [dsavell/docker-grav#30]
I have created the containe following your instructions. Everything seems to be working except for uploading files. For example, when trying to change the avatar the following error arises:

Unable to upload file photo.jpg: Missing a temporary folder

My docker_compose.yml file is:

```
version: '3'
services:
  grav:
    restart: always
    image: dsavell/grav:admin
    container_name: grav-website
    ports:
      - 6501:80
    environment:
      - DUID=1026
      - DGID=65126
    volumes:
      - /volume/docker/grav/backup:/var/www/grav/backup
      - /volume/docker/grav/logs:/var/www/grav/logs
      - /volume/docker/grav/user:/var/www/grav/user
      - /volume/docker/grav/tmp:/var/www/grav/tmp
```
