### ISSUE TITLE
Can't Install ANY themes and can't install some plugins!!!

### ISSUE THREAD

**Issue by BigDC** [dsavell/docker-grav#33]
I can not install any new themes. I go to the admin area and in the Themes section I click Add and select a theme and click install it will give me an error about something not being writeable, the error appears so quickly I can really see all of it.

The same thing happens with SOME not all but SOME plugins.

Also, may I make a suggestion of adding Nano text editor to the container. It would he a HUGE help, please?

Please help, please????

**Comment by BigDC** [comment]
By the way I use the dsavell/grav:admin tag and pull always from Docker Hub.

**Comment by BigDC** [comment]
Oh also, this is a NEW container.

**Comment by dsavell** [comment]
Hey @BigDC 

Can you show me how your running the container and steps to repeat I have just loaded up a test container, and I am able to install themes & plugins ok.

**Comment by dsavell** [comment]
Yes for nano, yes I can add this, it seems it has been requested a few times it will come in the next update.

**Comment by BigDC** [comment]
Is this what you mean by showing you how I run the container.....
sudo docker run -d --name BigDog TV --expose 80 --net bridge --restart always -v grav_data:/var/www/html -e VIRTUAL_HOST=bigdogtv.cf dsavell/grav:admin

**Comment by runarsf** [comment]
I'm having the same issue, haven't tested installing any themes yet, but only some plugins can be installed / updated. I'm using nginx to proxy pass to the grav container.
Creating a fresh container from the admin tag and attempting to update the *Flex Objects* plugin always fails with `Invalid AJAX response.` and `fwrite(): Unable to create temporary file, Check permissions in temporary files directory.`

This is my docker-compose.yml file:
```yml
version: "3"

services:
  grav:
    image: "dsavell/grav:admin"
    hostname: "grav"
    container_name: "grav"
    ports:
      - "6070:80"
    environment:
      DUID: "1000"
      DGID: "1000"
    volumes:
      - "./data/backup:/var/www/grav/backup"
      - "./data/logs:/var/www/grav/logs"
      - "./data/user:/var/www/grav/user"
    restart: "unless-stopped"
```
